version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password

  adminer:
    image: urtanto/back_ci
    restart: always
    ports:
      - 8080:8080