version: '3.1'

services:

  db:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: password

  adminer:
    image: urtanto/back_ci:master
    restart: always
    ports:
      - 8000:8000