# Generated by Django 4.2 on 2023-05-03 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_article_dirtlevel_producttype_service_stufftype_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='photo',
        ),
        migrations.AddField(
            model_name='photo',
            name='photo_after',
            field=models.ImageField(default='default.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='photo',
            name='photo_before',
            field=models.ImageField(default='default.png', upload_to=''),
        ),
    ]
