# Generated by Django 4.2 on 2023-05-03 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_article_name_alter_photo_photo_after_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlackListToken',
        ),
    ]
