# Generated by Django 4.2 on 2023-05-04 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_order_taken'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DirtLevel',
            new_name='DirtType',
        ),
        migrations.RenameField(
            model_name='dirttype',
            old_name='level',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='level_of_dirt',
            new_name='type_of_dirt',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='type_of_time',
        ),
        migrations.AddField(
            model_name='order',
            name='extra_services',
            field=models.TextField(default=''),
        ),
    ]
