# Generated by Django 4.2 on 2023-05-04 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_rename_dirtlevel_dirttype_rename_level_dirttype_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dirttype',
            name='type',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='type',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='stufftype',
            name='type',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='timetype',
            name='type',
            field=models.CharField(max_length=255),
        ),
    ]
