name: CI

on:
  push:
    branches:
      - master
#    path-ignore:
#      - '.github/workflows/*'

jobs:
  code_style:
    runs-on: [ ubuntu-latest ]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v1
        with:
          python-version: 3.10.11
      - name: Cache pythons dependencies
        uses: actions/cache@v3
        with:
          path: ~/.local/lib/python3.10/site-packages
          key: python-packages-${{ hashFiles('**requirements.txt') }}
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: CodeStyle
        run: pylint .
  tests:
    runs-on: [ ubuntu-latest ]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v1
        with:
          python-version: 3.10.11
      - name: Cache pythons dependencies
        uses: actions/cache@v3
        with:
          path: ~/.local/lib/python3.10/site-packages
          key: python-packages-${{ hashFiles('**requirements.txt') }}
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Tests
        run: python manage.py test
  build_and_pub:
    needs: [ tests, code_style ]
    runs-on: [ ubuntu-latest ]
    env:
      LOGIN: ${{ secrets.DOCKER_LOGIN }}
      NAME_BACK: ${{ secrets.DOCKER_BACK_NAME }}
      NAME_FRONT: ${{ secrets.DOCKER_FRONT_NAME }}
    steps:
      - name: Login to docker
        run: echo ${{ secrets.DOCKER_TOKEN }} | docker login -u ${{ secrets.DOCKER_LOGIN }} --password-stdin
      - uses: actions/checkout@v3
      - name: Build image
        run: docker build . -t $LOGIN/$NAME_BACK:${GITHUB_REF:11}
      - name: Push image to docker
        run: docker push $LOGIN/$NAME_BACK:${GITHUB_REF:11}
