name: CI

on:
  push:
    branches:
      - master

jobs:
  run_tests:
    runs-on: [ ubuntu-latest ]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v1
        with:
          python-version: 3.10
          cache: 'pip'
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: CodeStyle
        run: pylint .
      - name: Tests
        run: python manage.py test
  build_and_pub:
    needs: [ run_tests ]
    runs-on: [ ubuntu-latest ]
    env:
      LOGIN: ${{ secrets.DOCKER_LOGIN }}
      NAME_BACK: ${{ secrets.DOCKER_BACK_NAME }}
      NAME_FRONT: ${{ secrets.DOCKER_FRONT_NAME }}
    steps:
      - name: Login to docker
        run: echo ${{ secrets.DOCKER_TOKEN }} | docker login -u ${{ secrets.DOCKER_LOGIN }} --password-stdin
      - uses: actions/checkout@master
      - name: Build image
        run: docker build . -t $LOGIN/$NAME_BACK:${GITHUB_REF:11}
      - name: Push image to docker
        run: docker push $LOGIN/$NAME_BACK:${GITHUB_REF:11}
